// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3L_kj31k98IpyQw7J_dT9Qb3fq_Kfsro',
    appId: '1:935267958181:web:2df9559922e194e9633c4c',
    messagingSenderId: '935267958181',
    projectId: 'simu-kurizy',
    authDomain: 'simu-kurizy.firebaseapp.com',
    storageBucket: 'simu-kurizy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ_sf4NLr5FWg96_-IfSO459-jIjiOnSE',
    appId: '1:935267958181:android:c6a6753c3d8330b4633c4c',
    messagingSenderId: '935267958181',
    projectId: 'simu-kurizy',
    storageBucket: 'simu-kurizy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB35MQnvU-yoVxTqWDOsa1W3n7PsDn-2jY',
    appId: '1:935267958181:ios:202f6931be61bbdc633c4c',
    messagingSenderId: '935267958181',
    projectId: 'simu-kurizy',
    storageBucket: 'simu-kurizy.firebasestorage.app',
    iosBundleId: 'com.example.simpleSimu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB35MQnvU-yoVxTqWDOsa1W3n7PsDn-2jY',
    appId: '1:935267958181:ios:202f6931be61bbdc633c4c',
    messagingSenderId: '935267958181',
    projectId: 'simu-kurizy',
    storageBucket: 'simu-kurizy.firebasestorage.app',
    iosBundleId: 'com.example.simpleSimu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3L_kj31k98IpyQw7J_dT9Qb3fq_Kfsro',
    appId: '1:935267958181:web:7dc8824613979160633c4c',
    messagingSenderId: '935267958181',
    projectId: 'simu-kurizy',
    authDomain: 'simu-kurizy.firebaseapp.com',
    storageBucket: 'simu-kurizy.firebasestorage.app',
  );
}
